apiVersion: v1
kind: Service
metadata:
  labels:
    app: pgadmin-uat
  name: pgadmin-uat
  namespace: database-uat
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: pgadmin-uat