apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgresql-dev
  name: postgresql-dev
  namespace: database-dev
spec:
  ports:
  - name: proxy
    port: 54321
    protocol: TCP
    targetPort: 5432
  selector:
    app.kubernetes.io/component: primary
    app.kubernetes.io/instance: database-dev
    app.kubernetes.io/name: postgresql
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster