apiVersion: v1
kind: Service
metadata:
  labels:
    app: pgadmin-prd
  name: pgadmin-prd
  namespace: database-prd
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: pgadmin-prd