apiVersion: v1
kind: Service
metadata:
  labels:
    app: pgadmin-dev
  name: pgadmin-dev
  namespace: database-dev
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: pgadmin-dev