apiVersion: v1
kind: Service
metadata:
  labels:
    app: pgadmin-sit
  name: pgadmin-sit
  namespace: database-sit
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: pgadmin-sit